const SampleListData=[
    {
        id:1, 
        patientName:"Noor Khan",
        age:25, 
        phone_number:9886427856,
        date_of_collection: "none", 
        type:"biospy",
        origin: "blood", 
        date_of_birth:"10/01/2022",
        symptoms:"hiuahgjksfhgkjfsjknjkfnkjf",
        comments:"nkjahgjkhsfkjg",
        predictedLabel: "none", 
        humanLabel: "none", 
        SeeMore:"http://localhost:3000/login",

    },
    {
        id:2, 
        patientName:"Rapsan Jani", 
        age:26,
        date_of_collection: "none", 
        type:"biospy",
        origin: "blood", 
        date_of_birth:"10/01/2022",
        symptoms:"hiuahgjksfhgkjfsjknjkfnkjf",
        comments:"nkjahgjkhsfkjg",
        predictedLabel: "none", 
        humanLabel: "none", 
        SeeMore:"http://localhost:3000/login",
    },
    {
        id:3, 
        patientName:"Monika Singh", 
        age:18, 
        date_of_collection: "none", 
        type:"biospy",
        origin: "blood", 
        date_of_birth:"10/01/2022",
        symptoms:"hiuahgjksfhgkjfsjknjkfnkjf",
        comments:"nkjahgjkhsfkjg",
        predictedLabel: "none", 
        humanLabel: "none", 
        SeeMore:"http://localhost:3000/login",
    },
    {
        id:4, 
        patientName:"Sunil Kumar", 
        age:22, 
        date_of_collection: "none", 
        type:"biospy",
        origin: "blood", 
        date_of_birth:"10/01/2022",
        symptoms:"hiuahgjksfhgkjfsjknjkfnkjf",
        comments:"nkjahgjkhsfkjg",
        predictedLabel: "none", 
        humanLabel: "none", 
        SeeMore:"http://localhost:3000/login",
    },
    {
        id:5, 
        patientName:"Kajol Kumari", 
        age: 21, 
        date_of_collection: "none", 
        type:"biospy",
        origin: "blood", 
        date_of_birth:"10/01/2022",
        symptoms:"hiuahgjksfhgkjfsjknjkfnkjf",
        comments:"nkjahgjkhsfkjg",
        predictedLabel: "none", 
        humanLabel: "none", 
        SeeMore:"http://localhost:3000/login",
    },
    {
        id:6, 
        patientName:"Noor Khan", 
        age:25, 
        date_of_collection: "none", 
        type:"biospy",
        origin: "blood", 
        date_of_birth:"10/01/2022",
        symptoms:"hiuahgjksfhgkjfsjknjkfnkjf",
        comments:"nkjahgjkhsfkjg",
        predictedLabel: "none", 
        humanLabel: "none", 
        SeeMore:"http://localhost:3000/login",
    },
    {
        id:7, 
        patientName:"Rapsan Jani", 
        age:26, 
        date_of_collection: "none", 
        type:"biospy",
        origin: "blood", 
        date_of_birth:"10/01/2022",
        symptoms:"hiuahgjksfhgkjfsjknjkfnkjf",
        comments:"nkjahgjkhsfkjg",
        predictedLabel: "none", 
        humanLabel: "none", 
        SeeMore:"http://localhost:3000/login",
    },
    {
        id:8, 
        patientName:"Monika Singh", 
        age:18, 
        date_of_collection: "none", 
        type:"biospy",
        origin: "blood", 
        date_of_birth:"10/01/2022",
        symptoms:"hiuahgjksfhgkjfsjknjkfnkjf",
        comments:"nkjahgjkhsfkjg",
        predictedLabel: "none", 
        humanLabel: "none", 
        SeeMore:"http://localhost:3000/login",
    },
    {
        id:9, 
        patientName:"Sunil Kumar", 
        age:22, 
        date_of_collection: "none", 
        type:"biospy",
        origin: "blood", 
        date_of_birth:"10/01/2022",
        symptoms:"hiuahgjksfhgkjfsjknjkfnkjf",
        comments:"nkjahgjkhsfkjg",
        predictedLabel: "none", 
        humanLabel: "none", 
        SeeMore:"http://localhost:3000/login",
    },
    {
        id:10, 
        patientName:"Kajol Kumari", 
        age: 21, 
        date_of_collection: "none", 
        type:"biospy",
        origin: "blood", 
        date_of_birth:"10/01/2022",
        symptoms:"hiuahgjksfhgkjfsjknjkfnkjf",
        comments:"nkjahgjkhsfkjg",
        predictedLabel: "none", 
        humanLabel: "none", 
        SeeMore:"http://localhost:3000/login",
    }
]
export default SampleListData;